config/routes.rb
Rails.application.routes.draw do
  root to: "pages_static#index"
  resources :songs, except: :edit
  resources :setlists
  get :broadcast, to: "pages_static#broadcast"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/setlist.rb
class Setlist < ApplicationRecord
  include SongsHelper

  has_many :setlist_positions
  has_many :songs, through: :setlist_positions

  def number_of_songs
    songs.length
  end

  def songs_with_spid
    the_songs = Array.new
    setlist_positions.order(:position).each do |sp|
      song = sp.song
      song.setlist_position_id = sp.id
      the_songs.push(song)
    end
    the_songs
  end

  def duration
    songs.select { |s| !s.duration.nil? }.sum(&:duration)
  end

  def duration_f
    duration_formated(duration)
  end
end

app/models/setlist_position.rb
class SetlistPosition < ApplicationRecord
  belongs_to :song
  belongs_to :setlist
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :setlist_positions
  has_many :setlists, through: :setlist_positions

  attr_accessor :setlist_position_id
  attr_accessor :duration_formated
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_static_controller.rb
class PagesStaticController < ApplicationController
  def index
  end

  def broadcast
    @setlists = Setlist.all.order(updated_at: :desc).to_json
    @songs = Song.all.order(updated_at: :desc).to_json
  end
end

app/controllers/setlists_controller.rb
class SetlistsController < ApplicationController
  # GET /setlists
  def index
    @setlists = Setlist.all.order(:name).to_json(methods: [:number_of_songs, :duration_f])
  end

  # GET /setlists/new
  def new
    @setlist = Setlist.new
  end

  # POST /setlists
  def create
    @setlist = Setlist.new(setlist_params)
    respond_to do |format|
      if @setlist.save
        format.html { redirect_to setlist_path(@setlist), turbolinks: true }
      else
        format.html { render :edit }
      end
    end
  end

  # GET /setlists/:id
  def show
    @setlist = Setlist.find(params[:id])
    @setlist_songs = @setlist.songs_with_spid.to_json(methods: [:setlist_position_id])

    @songs = (Song.all.order(:title)).to_json
  end

  # PUT /setlists/:id
  def update
    @setlist = Setlist.find(params[:id])

    if params[:songs]
      
      raw_songs = JSON.parse(params[:songs])

      raw_songs.each do |raw_song|
        if raw_song["setlist_position_id"].nil?
          song = Song.find_by(id: raw_song["id"])
          unless song.nil?
            sp = SetlistPosition.create(setlist: @setlist, song: song, position: @setlist.songs.length + 1) 
            raw_song["setlist_position_id"] = sp.id
          end
        end
      end

      @setlist.setlist_positions.each do |sp|
        raw_song = raw_songs.find { |s| s["setlist_position_id"] == sp.id }
        if raw_song
          sp.update(position: raw_songs.index(raw_song) + 1)
        else
          sp.destroy
        end
      end

    end

    @setlist.update(setlist_params)

    respond_to do |format|
      format.html { redirect_to setlists_path }
    end
  end

  private

  def setlist_params
    params.require(:setlist).permit(
      :name
    )
  end

  def difference(original, other)
    h = other.each_with_object(Hash.new(0)) { |e,h| h[e] += 1 }
    original.reject { |e| h[e] > 0 && h[e] -= 1 }
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :update, :destroy]

  # GET /songs
  def index
    @songs = Song.all.order(:title)
    @songs.each { |song| song.duration_formated = helpers.duration_formated(song.duration) }
    @songs = @songs.to_json(methods: [:duration_formated])
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # POST /songs
  def create
    @song = Song.new(song_params)
    @song.duration = helpers.duration_seconds(params[:song][:duration_formated])
    respond_to do |format|
      if @song.save
        format.html { redirect_to song_path(@song), turbolinks: true }
      else
        format.html { render :edit }
      end
    end
  end

  # GET /songs/:id
  def show
    @song.duration_formated = helpers.duration_formated(@song.duration)
    if !@song.chords || @song.chords.empty?
      @song.chords = "[]"
    end
    @chords = @song.chords.to_json
  end

  # PUT /songs/:id
  def update
    @song.duration = helpers.duration_seconds(params[:song][:duration_formated])
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to songs_path, turbolinks: true }
      else
        format.html { render :show }
      end
    end
  end

  # DESTROY /songs/:id
  def destroy
    respond_to do |format|
      if @song.destroy
        format.html { redirect_to songs_path, turbolinks: true }
      else
        format.html { render :show }
      end
    end
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(
      :title,
      :artist,
      :bpm,
      :duration_formated,
      :chords
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_static_helper.rb
module PagesStaticHelper
end

app/helpers/setlists_helper.rb
module SetlistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
  def duration_seconds(duration)
    result = duration.split(/'|"/)
    if result.any?
      if result.length == 2
        result[0].to_i*60 + result[1].to_i
      elsif result.length == 3
        result[0].to_i*3600 + result[1].to_i*60 + result[2].to_i
      end
    elsif duration.is_a? Integer
      duration
    else
      nil
    end
  end

  def duration_formated(duration)
    if duration
      duration >= 3600 ? Time.at(duration).utc.strftime("%H'%M'%S") : Time.at(duration).utc.strftime("%M'%S")
    else
      ""
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Display</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render "layouts/shared/sidebar" %>
    <div class="main">
        <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/shared/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar__header">
    <div class="sidebar__logo">
      <%= image_pack_tag('logos/logo_text.svg') %>
    </div>
    <div class="sidebar__menu">
      <span class="icon-text-align-justify"></span>
    </div>
  </div>
  <div class="sidebar__nav">
    <div class="sidebar__item">
      <div class="link">
        <span class="icon-music-note"></span>
        <%= link_to "Chants", songs_url, class: "subtitle-2" %>
      </div>
      <div class="action">
        <%= link_to new_song_url do %>
          <span class="action__add icon-plus"></span>
        <% end %>
      </div>
    </div>
    <div class="sidebar__item">
      <div class="link">
        <span class="icon-player-list"></span>
        <%= link_to "Setlists", setlists_url, class: "subtitle-2" %>
      </div>
      <div class="action">
        <%= link_to new_setlist_url do %>
          <span class="action__add icon-plus"></span>
        <% end %>
      </div>
    </div>
    <div class="sidebar__item">
      <div class="link">
        <span class="icon-broadcast"></span>
        <%= link_to "Commencer une diffusion", broadcast_url, class: "subtitle-2" %>
      </div>
    </div>
  </div>
</div>

app/views/pages_static/broadcast.html.erb
<div data-behavior="vue" data-component="broadcast">

    <div class="flex-content">
        <div class="container">
            <h2 class="subtitle-1">Écrans disponibles</h2>

            <div class="screen__form">
                <input type="text" v-model="screenName" placeholder="Nommez votre écran">
                <span class="separator"></span>
                <button>
                    <span class="icon-broadcast"></span>
                    Diffuser sur cet écran
                </button>
            </div>
        </div>

        <div class="container">
            <h2 class="subtitle-1">Setlists et chants</h2>

            <div class="entity__association">
                <div class="search">
                    <input type="text" v-model="filter" placeholder='Rechercher un titre/setlist' class="search__input">
                </div>

                <pin-list :lists="[setlists_list, songs_list]" v-bind:separate="true"/>
            </div>

        </div>
    </div>

</div>

<%= javascript_tag do %>
  var songs_data = <%= @songs.html_safe %>
  var setlists_data = <%= @setlists.html_safe %>
<% end %>

app/views/setlists/index.html.erb
<div class="container">
  <h1 class="title-3">Setlists</h1>
</div>

<div data-behavior="vue" data-component="setlists" id="setlists">

  <table-display
    url_new="<%= new_setlist_path %>"
    new_link_text="Ajouter"
    placeholder="Rechercher par nom &#xea30;"
    :data="setlists"
    :filter_fc="filter" 
  >
    <template v-slot:table_head>
      <th>Nom</th>
      <th>Nombre de titres</th>
      <th>Durée totale</th>
    </template>

    <template v-slot:table_item="{ item: setlist }">
      <td>{{ setlist.name }}</td>
      <td>{{ setlist.number_of_songs }}</td>
      <td>{{ setlist.duration_f }}</td>
      <td><a v-bind:href="url(setlist)">Modifier</a></td>
    </template>

  </table-display>

</div>

<%= javascript_tag do %>
  var setlists_data = <%= @setlists.html_safe %>
<% end %>

app/views/setlists/new.html.erb
<div class="container">
  <%= form_for @setlist do |f| %>
    <%= render "setlists/shared/form", f: f %>
  <% end %>
</div>

app/views/setlists/shared/_form.html.erb
<div class="row middle-xs">
  <div class="col-xs-6 col-md-7">
    <div class="field">
      <%= f.label :name, "Nom*" %>
      <%= f.text_field :name, placeholder: "Nom", required: true, class: "subtitle-1" %>
    </div>
  </div>
  <div class="col-xs-6 col-md-5 end-xs">
    <%= f.submit "Enregistrer" %>
  </div>
</div>

app/views/setlists/show.html.erb
<div class="row setlist" data-behavior="vue" data-component="setlist">
  <div class="content col-xs-12 col-sm-7 col-lg-8">
    <div class="container">
      <%= form_for @setlist do |f| %>
        <%= render "setlists/shared/form", f: f %>
        <input type="hidden" name="songs" v-bind:value="JSON.stringify(setlist_songs)">
      <% end %>

      <div class="informations">
        <p>Durée : <span>{{ setlist_duration }}</span></p>
        <p>Nombre de titres : <span>{{ setlist_songs.length }}</span></p>
      </div>

      <div class="setlist__dragzone">
        <draggable class="list-group" :list="setlist_songs" group="setlist" @add="onAdd" draggable=".drag">
          <div v-for="(song, index) in setlist_songs" :key="index" class="setlist__item drag">
            <span class="subtitle-2">{{ index + 1 }}</span>
            <song-item class="list-group-item setlist__song" :song="song">
              <template v-slot:actions>
                <span class="icon-minus actions text-orange" @click="deleteSong(index)"></span>
              </template>
            </song-item>
          </div>
          <div class="setlist__item helper">
            <span class="subtitle-2">{{ setlist_songs.length + 1 }}</span>
            <div class="setlist__songItem-helper"></div>
          </div>
        </draggable>
        
      </div>
    </div>
  </div>

  <div class="setlist__panel col-sm-5 col-lg-4">
    <panel :songs="songs">
      <template v-slot:songs-container="data">
        <draggable class="list-group" :list="data.filtered_songs" :group="{ name: 'setlist', pull: 'clone', put: false }" :sort="true">
          <song-item class="list-group-item mb-10" v-for="(song, index) in data.filtered_songs" :key="index" :song="song"/>
        </draggable>
      </template>
    </panel>
  </div>
</div>


<%= javascript_tag do %>
  var songs_data = <%= @songs.html_safe %>
  var setlist_songs_data = <%= @setlist_songs.html_safe %>
<% end %>

app/views/songs/index.html.erb
<div class="container">
  <h1 class="title-3">Chants</h1>
</div>

<div data-behavior="vue" data-component="songs" id="songs">
  <table-display
    url_new="<%= new_song_path %>"
    new_link_text="Ajouter"
    placeholder="Rechercher par titre/artiste &#xea30;"
    :data="songs"
    :filter_fc="filter" 
  >
    <template v-slot:table_head>
      <th>Titre</th>
      <th>Artiste</th>
      <th>Durée</th>
    </template>

    <template v-slot:table_item="{ item: song }">
      <td>{{ song.title }}</td>
      <td>{{ song.artist }}</td>
      <td>{{ song.duration_formated }}</td>
      <td><a v-bind:href="url(song)">Modifier</a></td>
    </template>

  </table-display>
</div>

<%= javascript_tag do %>
  var songs_data = <%= @songs.html_safe %>
<% end %>

app/views/songs/new.html.erb
<div class="container">
  <%= form_for @song do |f| %>
    <%= render "songs/shared/form", f: f %>
  <% end %>
</div>

app/views/songs/shared/_form.html.erb
<div class="row middle-xs">
  <div class="col-xs-6 col-md-8">
    <div class="field">
      <%= f.label :title, "Titre*" %>
      <%= f.text_field :title, placeholder: "Titre", required: true, class: "subtitle-1" %>
    </div>
  </div>

  <div class="col-xs-6 col-md-4 end-xs">
    <% if f.object.persisted? %>
      <%= link_to "Supprimer", song_path(f.object), method: :delete, class: "mr-2 delete" if f.object.setlists.empty? %>
    <% end %>
    <%= f.submit "Enregistrer" %>
  </div>
</div>
<div class="row">
  <div class="mr-2">
    <div class="field">
    <%= f.label :artist, "Artiste" %>
    <%= f.text_field :artist, placeholder: "Artiste" %>
    </div>
  </div>
  <div class="mr-2">
    <div class="field">
      <%= f.label :duration_formated, "Durée" %>
      <%= f.text_field :duration_formated, placeholder: "Durée" %>
    </div>    
  </div>
  <div class="mr-2">
    <div class="field">
      <%= f.label :bpm, "BPM" %>
      <%= f.text_field :bpm, placeholder: "BPM" %>
    </div>    
  </div>
</div>

app/views/songs/show.html.erb
<div class="container">
  <%= form_for @song do |f| %>
    <%= render "songs/shared/form", f: f %>

    <h5>Structure</h5>

    <div data-behavior="vue" id="chords" data-component="song">
      <app v-bind:chords="filtered_chords"></app>
      <input type="hidden" name="song[chords]" v-bind:value="JSON.stringify(chords)">
    </div>

  <% end %>
</div>


<%= javascript_tag do %>
  var chords_data = JSON.parse(<%= @chords.html_safe %>)
<% end %>